language: julia
os:
  - linux
  - osx
dist: xenial
services:
  - xvfb
julia:
  - 1.5.4
  - 1.6.0
  - nightly
notifications:
  email: false
env:
  - JULIA_DEBUG=GR
#  - JULIA_DEBUG=GR JULIA_GR_PROVIDER=GR
